// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjmMu9Suu1pjvk53hczCXb3HqochvmVE',
    appId: '1:714308862024:web:4acdaba11f3dab15d9187d',
    messagingSenderId: '714308862024',
    projectId: 'utmfirebasemapauth',
    authDomain: 'utmfirebasemapauth.firebaseapp.com',
    storageBucket: 'utmfirebasemapauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDU_8pqa5x_3drkobTOqGV9W4ZcR35SwM',
    appId: '1:714308862024:android:83b133b4e4f88e74d9187d',
    messagingSenderId: '714308862024',
    projectId: 'utmfirebasemapauth',
    storageBucket: 'utmfirebasemapauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmfUYKxu0CTh0SbG4fzGpAb0lds3W0LuI',
    appId: '1:714308862024:ios:4dae8ebefdbf78dad9187d',
    messagingSenderId: '714308862024',
    projectId: 'utmfirebasemapauth',
    storageBucket: 'utmfirebasemapauth.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmfUYKxu0CTh0SbG4fzGpAb0lds3W0LuI',
    appId: '1:714308862024:ios:4dae8ebefdbf78dad9187d',
    messagingSenderId: '714308862024',
    projectId: 'utmfirebasemapauth',
    storageBucket: 'utmfirebasemapauth.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjmMu9Suu1pjvk53hczCXb3HqochvmVE',
    appId: '1:714308862024:web:82b3295a45b3cc83d9187d',
    messagingSenderId: '714308862024',
    projectId: 'utmfirebasemapauth',
    authDomain: 'utmfirebasemapauth.firebaseapp.com',
    storageBucket: 'utmfirebasemapauth.appspot.com',
  );
}
